import {createConstants} from '../utils';

enum CONSTANTS {
 LOGIN_USER_REQUEST,
 LOGIN_USER_FAILURE,
 LOGIN_USER_SUCCESS,
 LOGOUT_USER,
 FETCH_PROTECTED_DATA_REQUEST,
 RECEIVE_PROTECTED_DATA
}

export default CONSTANTS;
